project:
  name: aws-alphafold2
  role_name: AWS-AlphaFold-GitLab-CI-Role
  s3_bucket: aws-batch-architecture-for-alphafold-public-artifacts
  regions:
    - us-east-1
    - us-east-2
    - us-west-2
tests:
  default:
    template: infrastructure/alphafold-cfn-packaged.yaml
