project:
  name: aws-alphafold2
  package_lambda: false
  s3_bucket: aws-batch-architecture-for-alphafold-public-artifacts
  regions:
    - us-east-1
tests:
  default:
    template: infrastructure/alphafold-cfn-packaged.yaml
