AWSTemplateFormatVersion: 2010-09-09
Description: Root stack for running AWS Batch Architecture for AlphaFold.
Parameters:
  ApplicationName:
    Type: String
    Default: AlphaFold
  StackAvailabilityZone:
    Type: String
    AllowedValues:
    - a
    - b
    - c
    Default: a
  VPC:
    Description: (Optional) ID of VPC to use. If left empty, a new VPC will be created.
    Type: String
    Default: ''
  DefaultSecurityGroup:
    Description: (Optional) ID of security group to use. If left empty, a new VPC
      will be created.
    Type: String
    Default: ''
  Subnet:
    Description: (Optional) ID of private subnet to use. If left empty, a new VPC
      will be created.
    Type: String
    Default: ''
  FileSystemId:
    Description: (Optional) ID of FSX for Lustre  to use. If left empty, a new FSx
      for Lustre instance will be created.
    Type: String
    Default: ''
  FileSystemMountName:
    Description: (Optional) Mount name of FSX for Lustre to use. If left empty, a
      new FSx for Lustre instance will be created.
    Type: String
    Default: ''
  Environment:
    Description: Leave this as "main" unless you are testing a pre-release version
      of this architecture.
    Type: String
    Default: main
    AllowedValues:
    - main
    - dev
  LaunchSageMakerNotebook:
    Type: String
    Default: Y
    Description: Create a SageMaker Notebook Instance.
    AllowedValues:
    - Y
    - N
  AlphaFoldVersion:
    Description: AlphaFold release to include as part of the job container
    Type: String
    Default: v2.1.2
    AllowedValues:
    - v2.1.2
Conditions:
  CreateNetwork:
    Fn::Or:
    - Fn::Equals:
      - Ref: VPC
      - ''
    - Fn::Equals:
      - Ref: DefaultSecurityGroup
      - ''
    - Fn::Equals:
      - Ref: Subnet
      - ''
  CreateFileSystem:
    Fn::Or:
    - Fn::Equals:
      - Ref: FileSystemId
      - ''
    - Fn::Equals:
      - Ref: FileSystemMountName
      - ''
    - Fn::Equals:
      - Ref: VPC
      - ''
    - Fn::Equals:
      - Ref: DefaultSecurityGroup
      - ''
    - Fn::Equals:
      - Ref: Subnet
      - ''
Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Condition: CreateNetwork
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/alphafold-cfn-build/a90b96840d9ea1bfc9ef50b3511d4541.template
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        StackAvailabilityZone:
          Fn::Join:
          - ''
          - - Ref: AWS::Region
            - Ref: StackAvailabilityZone
  FileSystem:
    Type: AWS::CloudFormation::Stack
    Condition: CreateFileSystem
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/alphafold-cfn-build/b6c438e303708ff9dcc2d4be0dd49a81.template
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        DefaultSecurityGroup:
          Fn::If:
          - CreateNetwork
          - Fn::GetAtt:
            - Network
            - Outputs.DefaultSecurityGroup
          - Ref: DefaultSecurityGroup
        FSXForLustreStorageCapacity: 1200
        FSxForLustreThroughput: 500
        Subnet:
          Fn::If:
          - CreateNetwork
          - Fn::GetAtt:
            - Network
            - Outputs.PrivateSubnet
          - Ref: Subnet
  ContainerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/alphafold-cfn-build/54591531e2f973a68d86f38e299db866.template
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        Environment:
          Ref: Environment
        AlphaFoldVersion:
          Ref: AlphaFoldVersion
  BatchEnvironment:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/alphafold-cfn-build/5a55771a0b134e7c8a359f7e5fec8bc6.template
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        DefaultSecurityGroupID:
          Fn::If:
          - CreateNetwork
          - Fn::GetAtt:
            - Network
            - Outputs.DefaultSecurityGroup
          - Ref: DefaultSecurityGroup
        FileSystemId:
          Fn::If:
          - CreateFileSystem
          - Fn::GetAtt:
            - FileSystem
            - Outputs.FileSystemId
          - Ref: FileSystemId
        FileSystemMountName:
          Fn::If:
          - CreateFileSystem
          - Fn::GetAtt:
            - FileSystem
            - Outputs.FileSystemMountName
          - Ref: FileSystemMountName
        Subnet:
          Fn::If:
          - CreateNetwork
          - Fn::GetAtt:
            - Network
            - Outputs.PrivateSubnet
          - Ref: Subnet
        CodeRepositoryURI:
          Fn::GetAtt:
          - ContainerStack
          - Outputs.CodeRepositoryURI
        FoldingContainerRegistryURI:
          Fn::GetAtt:
          - ContainerStack
          - Outputs.FoldingContainerRegistryURI
        DownloadContainerRegistryURI:
          Fn::GetAtt:
          - ContainerStack
          - Outputs.DownloadContainerRegistryURI
        LaunchSageMakerNotebook:
          Ref: LaunchSageMakerNotebook
