# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Deploy with
# aws cloudformation package --template-file infrastructure/alphafold-cfn-root.yaml --output-template infrastructure/alphafold-cfn-packaged.yaml --s3-bucket alphafold-cfn-build
# aws cloudformation deploy --template-file infrastructure/alphafold-cfn-packaged.yaml --capabilities CAPABILITY_IAM --stack-name aws-batch-alphafold220603 --parameter-overrides DownloadFsxData=Y VPC=vpc-0ed8c8f15fe9244ae DefaultSecurityGroup=sg-023becfedd6b7d954 Subnet=subnet-040ae3cdbc5433c4e Environment=dev FileSystemId=fs-0e4ca95b6befaf3e1 FileSystemMountName=pkwztbmv
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Root stack for running AWS Batch Architecture for AlphaFold.

Parameters:
  ApplicationName:
    Type: String
    Default: AlphaFold
  AlphaFoldVersion:
    Description: AlphaFold release to include as part of the job container
    Type: String
    Default: v2.2.0
    AllowedValues:
      - v2.2.0
      - v2.1.2
  CleanUp:
    Description: Delete all resources when deleting stack, including data?
    Type: String
    Default: Y
    AllowedValues: [Y, N]      
  LaunchSageMakerNotebook:
    Type: String
    Default: Y
    Description: Create a SageMaker Notebook Instance.
    AllowedValues: [Y, N]       
  StackAvailabilityZone:
    Type: String
    AllowedValues: [a, b, c]
    Default: a    
  EnableSpotInstanceTypes:
    Type: String
    Default: Y
    Description: Should the stack include an additional CPU compute environment with spot instance types for cost savings?
    AllowedValues: [Y, N]      
  Environment:
    Description: Leave this as "main" unless you are testing a pre-release version of this architecture.
    Type: String
    Default: main
    AllowedValues:
      - main
      - dev
  VPC:
    Description: (Optional) ID of VPC to use. If left empty, a new VPC will be created.
    Type: String
    Default: ""     
  Subnet:
    Description: (Optional) ID of private subnet to use. If left empty, a new VPC will be created.
    Type: String
    Default: ""     
  DefaultSecurityGroup:
    Description: (Optional) ID of security group to use. If left empty, a new VPC will be created.
    Type: String
    Default: ""
  FileSystemId:
    Description: (Optional) ID of FSX for Lustre  to use. If left empty, a new FSx for Lustre instance will be created.
    Type: String
    Default: ""
  FileSystemMountName:
    Description: (Optional) Mount name of FSX for Lustre to use. If left empty, a new FSx for Lustre instance will be created.
    Type: String
    Default: ""    
  # DownloadFsxData:
  #   Description: Automatically populate FSx for Lustre file system with model parameters and sequence databases?
  #   Type: String
  #   Default: "N"

Conditions:
  CreateFileSystem:
    "Fn::Or":
      [
        "Fn::Equals": [Ref: FileSystemId, ""],
        "Fn::Equals": [Ref: FileSystemMountName, ""],
        "Fn::Equals": [Ref: VPC, ""],
        "Fn::Equals": [Ref: DefaultSecurityGroup, ""],
        "Fn::Equals": [Ref: Subnet, ""],
      ]
  CreateNetwork:
    "Fn::Or":
      [
        "Fn::Equals": [Ref: VPC, ""],
        "Fn::Equals": [Ref: DefaultSecurityGroup, ""],
        "Fn::Equals": [Ref: Subnet, ""],
      ]
  CreateSageMakerNotebook:
    "Fn::Equals": [Ref: "LaunchSageMakerNotebook", "Y"]
  CleanUp:
    "Fn::Equals": [Ref: "CleanUp", "Y"] 
  # DownloadFsxDataCondition:
  #   "Fn::Equals": [Ref: "DownloadFsxData", "Y"] 

Resources:
  Network:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateNetwork
    Properties:
      TemplateURL: alphafold-cfn-network.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        StackAvailabilityZone:
          "Fn::Join": ["", [Ref: "AWS::Region", Ref: StackAvailabilityZone]]

  FileSystem:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateFileSystem
    Properties:
      TemplateURL: alphafold-cfn-fsx-lustre.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        DefaultSecurityGroup:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.DefaultSecurityGroup
            - Ref: DefaultSecurityGroup
        FSXForLustreStorageCapacity: 1200
        FSxForLustreThroughput: 500
        Subnet:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.PrivateSubnet
            - Ref: Subnet

  Container:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: alphafold-cfn-container.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        Environment:
          Ref: Environment
        AlphaFoldVersion:
          Ref: AlphaFoldVersion

  BatchEnvironment:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: alphafold-cfn-batch.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        Subnet:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.PrivateSubnet
            - Ref: Subnet
        DefaultSecurityGroupID:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.DefaultSecurityGroup
            - Ref: DefaultSecurityGroup
        EnableSpotInstanceTypes:
          Ref: EnableSpotInstanceTypes
        FileSystemId:
          "Fn::If":
            - CreateFileSystem
            - "Fn::GetAtt": FileSystem.Outputs.FileSystemId
            - Ref: FileSystemId
        FileSystemMountName:
          "Fn::If":
            - CreateFileSystem
            - "Fn::GetAtt": FileSystem.Outputs.FileSystemMountName
            - Ref: FileSystemMountName
        FoldingContainerRegistryURI:
          "Fn::GetAtt": Container.Outputs.FoldingContainerRegistryURI
        DownloadContainerRegistryURI:
          "Fn::GetAtt": Container.Outputs.DownloadContainerRegistryURI

  Notebook:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateSageMakerNotebook
    Properties:
      TemplateURL: alphafold-cfn-notebook.yaml
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        Subnet:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.PrivateSubnet
            - Ref: Subnet
        DefaultSecurityGroupID:
          "Fn::If":
            - CreateNetwork
            - "Fn::GetAtt": Network.Outputs.DefaultSecurityGroup
            - Ref: DefaultSecurityGroup
        CodeRepositoryURI:
          "Fn::GetAtt": Container.Outputs.CodeRepositoryURI

  Cleanup:
    Type: "AWS::CloudFormation::Stack"
    Condition: CleanUp
    Properties:
      TemplateURL: alphafold-cfn-cleanup.yaml
      Parameters:
        # S3Bucket:
        #   "Fn::GetAtt": Container.Outputs.s3Bucket
        FoldingContainerRepo:
          "Fn::GetAtt": Container.Outputs.FoldingContainerRegistryName
        DownloadContainerRepo:
          "Fn::GetAtt": Container.Outputs.DownloadContainerRegistryName          

  # DownloadData:
  #   Type: "AWS::CloudFormation::Stack"
  #   DependsOn:
  #     - BatchEnvironment
  #   # Condition: DownloadFsxDataCondition
  #   Properties:
  #     TemplateURL: alphafold-cfn-download.yaml

Outputs:
  ApplicationName:
    Description: Name of the application
    Value:
      Ref: ApplicationName
